# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6-dev

brew_packages:
  - sashkab/python/python36

env:
  global:
    - PYTHON=python3.6

before_install:
  - $PYTHON --version
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H $PYTHON
  - $PYTHON -m pip install --upgrade pip
  - $PYTHON -m pip install phate

script:
  - R CMD build .
  - travis_wait 30 R CMD check *tar.gz

r_packages:
  - Matrix
  - ggplot2
  - reticulate
  - gridGraphics
  - cowplot

before_cache:
  - brew cleanup

cache: 
  - packages
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

warnings_are_errors: true
