# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

cache: 
  - packages
  - apt
  - directories:
    - $HOME/.cache/pip

apt:
  sources:
    - deadsnakes
  packages:
    - python3.6-dev

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

env:
  global:
    - PATH="$HOME/miniconda/bin:$PATH"
    - RETICULATE_PYTHON="$HOME/miniconda/bin/python"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew upgrade python; brew install sashkab/python/python36; fi
  - python3 -m pip install --upgrade pip
  - pip3 install phate

script:
  - R CMD build .
  - travis_wait 30 R CMD check *tar.gz

r_packages:
  - Matrix
  - ggplot2
  - reticulate
  - gridGraphics
  - cowplot

warnings_are_errors: true
